fieldLayouts:
  b55bf3d0-a381-4dbd-9a94-8f05b6c81cb1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: 'Vehicle name'
            label: 'Vehicle name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 01295f3e-b87b-463b-b873-f1fd5b46cc6f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2588d4e0-146c-4f8c-8190-b16f059d1a8a # Summary Text
            instructions: 'short text that describes the vehicle. About two sentences '
            label: 'Vehicle summary'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 449ea458-2815-40f4-a683-47145c99c7b1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7237bd34-fece-4929-bec1-720c95d92d41 # Car Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 679c379e-673e-4cf6-bf01-c6a21828bd96
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 565a57a5-2f31-4663-9cb4-fab70e79adef # Price Per Day
            instructions: 'the price per day for the vehicle in EUR'
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2bd44b3-6e8c-42a6-aad6-604c388ab890
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fe4e8cef-1812-4eca-bca5-91613ef11a4f # Data Value Seats
            instructions: 'the amount of seats in the vehicle (up to 7)'
            label: Seats
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ecd54a3-462f-4e6c-8174-34dd4b914e41
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5cfb29bb-4c0c-40f7-95f2-389dc86908a8 # Data Value Gears
            instructions: 'automatic or manual gear transmission'
            label: Transmission
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c069252-5ad8-48da-92be-135a3f6a2f3c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f1b472a5-f8c0-4d17-b887-70c016844a10 # Data Value Doors
            instructions: 'Amount of doors on the car'
            label: Doors
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40c82ebf-f6b5-4f55-85af-bfee8881f61b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 36fff91a-85e3-4ce4-90f5-8b88a212869b # text
            instructions: 'Full description of the vehicle'
            label: 'vehicle description'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79412a17-d081-45f2-ae14-e7f0efed1fe0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9a856196-f4cf-43a4-94f5-fc20410c6a7d
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: b5223d8f-0634-4917-9612-14a9bdac5d37 # Vehicles
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
