columnSuffix: oecnsufd
contentColumnType: char
fieldGroup: fd94f5d7-8f12-42b5-ad97-78bb9426820d # Global
handle: dataValueSeats
instructions: null
name: 'Data Value Seats'
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - label
          - '2'
        -
          - value
          - '2'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3'
        -
          - value
          - '3'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '4'
        -
          - value
          - '4'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '5'
        -
          - value
          - '5'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '6'
        -
          - value
          - '6'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '7'
        -
          - value
          - '7'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '8'
        -
          - value
          - '8'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '9'
        -
          - value
          - '9'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
